### ISSUE TITLE
there is a problem!!!

### ISSUE THREAD

**Issue by lxy443626128** [latte0/cartoonGAN#3]
UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  softmax_output = torch.nn.functional.softmax(output)
(R)t_loss:3.5914 t_loss_reg:2.8957, t_loss_adv:0.695739(0.50%)
Traceback (most recent call last):
  File "main.py", line 451, in <module>
    obj.train()
  File "main.py", line 360, in train
    animeblur_image_batch = Variable(anime_image_batch).cuda()
RuntimeError: Variable data has to be a tensor, but got Variable

**Comment by lxy443626128** [comment]
已解决~ 代码anime_image_batch   ——> animeblur_image_batch
